server:
  port: 9001

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        namespace: jade300
        server-addr: localhost:8848
  redis:
    port: 6379
    host: 127.0.0.1
    database: 10
    password:
    jedis:
      pool:
        min-idle: 5
        max-idle: -1
        max-active: 300
  ldap:
    base:
    urls:
    username:
    password:

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true