server:
  port: 9002

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  application:
    name: system-server
  cloud:
    nacos:
      discovery:
        namespace: jade300
        server-addr: localhost:8848
  redis:
    port: 6379
    host: 127.0.0.1
    database: 10
    password:
    jedis:
      pool:
        min-idle: 5
        max-idle: -1
        max-active: 300
  datasource:
    dynamic:
      hikari:
        min-idle: 2
        max-pool-size: 8
        idle-timeout: 60000
        keepalive-time: 30000
        max-lifetime: 500000
        connection-timeout: 60000
        is-auto-commit: true
      druid:
        max-active: 20
        min-idle: 5
        initial-size: 5
        filters: stat,slf4j
        min-evictable-idle-time-millis: 600000
        max-pool-prepared-statement-per-connection-size: 20
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jade?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: off

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
